# Generated by Django 6.0.1 on 2026-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_startapp", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                related_name="posts", to="social_startapp.hashtag"
            ),
        ),
    ]
