# Generated by Django 6.0.1 on 2026-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_startapp", "0003_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_startapp.hashtag"
            ),
        ),
    ]
