# Generated by Django 6.0.1 on 2026-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="no_search-da5823a9-70bf-4221-88e9-3bf377a1c397",
                max_length=52,
                unique=True,
            ),
        ),
    ]
